"""
Django settings for WEB project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from django.views.static import serve

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname (os.path.dirname (os.path.abspath (__file__)))
sys.path.insert (0,BASE_DIR)
sys.path.insert (0, os.path.join (BASE_DIR, 'apps'))
sys.path.insert (0, os.path.join (BASE_DIR, 'extra_apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
# 图片的路径
MEDIA_ROOT = os.path.join (BASE_DIR, 'media')  # 图片存取的绝对路径
MEDIA_URL = '/media/'  # 图片存取的相对路径
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*)7#@_pyqq7wzvdd@9^^**w4@iud356jndp(%ox(37-wdp)%)j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 生产环境开启

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL ='Authlogin.Users'
# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'blog',
	'Authlogin',
	'LigthApp',
	'ckeditor',
	'imagekit',
	'rest_framework',
	'apps.blog.templatetags',
]
LOGIN_URL = '/auth/login/'
MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'apps.LigthApp.mymidleware.Accessfrequency',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WEB.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join (BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'apps.blog.views.global_variable',  # blog.views中定义的全局函数
			],
		},
	},
]

WSGI_APPLICATION = 'WEB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
#mysql设置
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'web',  # 你的数据库名称
		'USER': 'root',  # 你的数据库用户名
		'PASSWORD': '123456',  # 你的数据库密码
		'HOST': '127.0.0.1',  # 你的数据库主机，留空默认为localhost
		'PORT': '3306',  # 你的数据库端口
	}
}
# 设置打印日志到屏幕


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]
# settings.py
...
# ckeditor配置
CKEDITOR_CONFIGS = {
    # 将这份配置命名为 my_config
    'my_config': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'],
            # 在工具栏中添加该功能的按钮
            ['CodeSnippet'], ['Source'],

        ],
        'toolbar': 'Full',
        'height': 291,
        'width': 835,
        'filebrowserWindowWidth': 940,
        'filebrowserWindowHeight': 725,
        # 添加的插件
        'extraPlugins': 'codesnippet',
    }
}





# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
	os.path.join (BASE_DIR, 'static'),
]
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
